<a href="https://colab.research.google.com/github/UbongErnest/MyMarket/blob/main/AI_PRACTICAL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd


In [2]:
df = pd.read_csv('/content/malaria_symptom_dataset_with_target.csv')

In [3]:
df.head(100)

,FVR,HGGDFVR,LWGDFVR,SUDONFVR,SWRFVR,CHLNRIG,HDACH,FTG,GENBDYPN,MSCBDYPN,JNTSWL,NUS,VMT,DIZ,NGTSWT,LTG,target
0,5,4,2,4,3,4,3,4,4,4,1,4,4,4,3,4,severe
1,2,3,4,3,4,2,1,2,1,1,1,2,2,1,2,1,mild
2,5,4,4,4,3,5,4,3,4,4,4,3,1,3,1,4,moderate
3,3,1,3,4,3,1,3,1,4,2,2,3,4,3,1,1,moderate
4,4,4,4,3,3,1,4,3,4,3,1,2,3,1,3,1,moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,4,1,1,3,1,3,3,3,3,3,1,1,1,1,1,2,mild
96,3,1,3,1,1,1,1,1,2,3,1,1,1,1,1,1,mild
97,3,1,1,1,1,1,2,1,1,1,1,1,1,2,1,1,mild
98,4,1,1,1,1,5,5,3,5,3,1,1,1,1,1,2,moderate


In [4]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import LabelEncoder

In [5]:
# Separate features (X) and target (y)
X = df.drop('target', axis=1)
y = df['target']

# Encode the target variable
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

In [6]:
# Initialize and train the Decision Tree Classifier
dtc = DecisionTreeClassifier(random_state=42)
dtc.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [8]:
# Make predictions on the test set
y_pred = dtc.predict(X_test)

# Evaluate the model
print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=label_encoder.classes_))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9259259259259259

Classification Report:
              precision    recall  f1-score   support

        mild       0.95      0.96      0.95       558
    moderate       0.89      0.85      0.87       220
      severe       0.50      0.60      0.55         5

    accuracy                           0.93       783
   macro avg       0.78      0.80      0.79       783
weighted avg       0.93      0.93      0.93       783


Confusion Matrix:
[[536  22   0]
 [ 31 186   3]
 [  0   2   3]]


In [9]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [10]:
# Define the Artificial Neural Network model
model = keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    layers.Dropout(0.3),
    layers.Dense(32, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(len(label_encoder.classes_), activation='softmax') # Output layer with softmax for multi-class classification
])

# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.2, verbose=0)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [11]:
# Make predictions on the test set
y_pred_ann_probs = model.predict(X_test)
y_pred_ann = tf.argmax(y_pred_ann_probs, axis=1)

# Evaluate the model
print(f"ANN Accuracy: {accuracy_score(y_test, y_pred_ann)}")
print("\nANN Classification Report:")
print(classification_report(y_test, y_pred_ann, target_names=label_encoder.classes_))
print("\nANN Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_ann))

25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step
ANN Accuracy: 0.9770114942528736

ANN Classification Report:
              precision    recall  f1-score   support

        mild       0.98      1.00      0.99       558
    moderate       0.98      0.94      0.96       220
      severe       1.00      0.20      0.33         5

    accuracy                           0.98       783
   macro avg       0.98      0.71      0.76       783
weighted avg       0.98      0.98      0.98       783


ANN Confusion Matrix:
[[557   1   0]
 [ 13 207   0]
 [  0   4   1]]


In [12]:
from sklearn.ensemble import RandomForestClassifier

In [13]:
# Initialize and train the Random Forest Classifier
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [14]:
# Make predictions on the test set
y_pred_rf = rf_model.predict(X_test)

# Evaluate the model
print(f"Random Forest Accuracy: {accuracy_score(y_test, y_pred_rf)}")
print("\nRandom Forest Classification Report:")
print(classification_report(y_test, y_pred_rf, target_names=label_encoder.classes_))
print("\nRandom Forest Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))

Random Forest Accuracy: 0.9706257982120051

Random Forest Classification Report:
              precision    recall  f1-score   support

        mild       0.97      0.99      0.98       558
    moderate       0.98      0.91      0.95       220
      severe       1.00      0.80      0.89         5

    accuracy                           0.97       783
   macro avg       0.98      0.90      0.94       783
weighted avg       0.97      0.97      0.97       783


Random Forest Confusion Matrix:
[[555   3   0]
 [ 19 201   0]
 [  0   1   4]]


In [15]:
from sklearn.svm import SVC

In [16]:
# Initialize and train the Support Vector Machine Classifier
svm_model = SVC(random_state=42)
svm_model.fit(X_train, y_train)

SVC(random_state=42)

In [17]:
# Make predictions on the test set
y_pred_svm = svm_model.predict(X_test)

# Evaluate the model
print(f"SVM Accuracy: {accuracy_score(y_test, y_pred_svm)}")
print("\nSVM Classification Report:")
print(classification_report(y_test, y_pred_svm, target_names=label_encoder.classes_))
print("\nSVM Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_svm))

SVM Accuracy: 0.9885057471264368

SVM Classification Report:
              precision    recall  f1-score   support

        mild       0.99      1.00      0.99       558
    moderate       0.99      0.97      0.98       220
      severe       1.00      0.60      0.75         5

    accuracy                           0.99       783
   macro avg       0.99      0.86      0.91       783
weighted avg       0.99      0.99      0.99       783


SVM Confusion Matrix:
[[557   1   0]
 [  6 214   0]
 [  0   2   3]]
